### ISSUE TITLE
href for codeblock.css looks into post folder rather than root folder

### ISSUE THREAD

**Issue by AntoineGlacet** [jdvp/jdvp-codetabs-commonmark#2]
in your reference to css and js files your refer to assets instead of /assets.

Therefore when building the site, jekyll look for css and js files in the post folder and not in the root.
When I correct locally it works fine, I will submit a pull request soon.

Sorry, my description of the problem might be a bit unclear, I will try to improve it.

**Comment by jdvp** [comment]
Merged #3 . Please check if the actual release of the changes in [v0.1.1](https://rubygems.org/gems/jdvp-codetabs-commonmark) fixes your issue! If so please feel free to close this one!

**Comment by jdvp** [comment]
Ok this actually broke something for my prod website but not locally... investigating lol

**Comment by jdvp** [comment]
@AntoineGlacet Please test on version v0.1.2
I made this change to account for the fact that some site (like mine lol) have different base urls:
https://github.com/jdvp/jdvp-codetabs-commonmark/commit/a7b7674f1d694d2fb919c6750dac8b37bc49b791

**Comment by AntoineGlacet** [comment]
@jdvp , sorry for the late answer, it works fine now thanks!
(I realize my fix was sloppy now!)

**Comment by jdvp** [comment]
@AntoineGlacet Perfect!! Thank you.

Also no worries, the fact that you brought it up at all and pointed me in the direction of the fix was incredibly helpful!!
