### ISSUE TITLE
codeCopyEnabled on certain part of code

### ISSUE THREAD

**Issue by Clement-Jean** [jdvp/jdvp-codetabs-commonmark#6]
An idea that I found when writing my last blog is that we could enable codeCopyEnabled on a certain part of the code block. An example of this is, I'm writing shell commands and I also want to display the result. However, I would like the reader to only copy the command (without the prompt, and without the result). Here is an example of what I have now:

```shell
$ cat repeated.txt | protoc --encode=PackedRepeated proto/repeated.proto | hexdump -C
00000000  0a 03 01 02 03                                    |.....|
00000005
```

In this case the codeCopyEnabled would only copy `cat repeated.txt | protoc --encode=PackedRepeated proto/repeated.proto | hexdump -C`.

I'm not sure how this can be done. Maybe with liquid tags but I'm not sure.

**Comment by jdvp** [comment]
Thanks for the idea, seems really useful to me. I've implemented in v1.0.0!

You should be able to accomplish the above using `codeCopyEnabled="0"`

You can see the release notes here : 
https://github.com/jdvp/jdvp-codetabs-commonmark/releases/tag/v1.1.0

And take a look at my sample article for usage info (in the **Advanced code copying** section): [Testing Code Tabs](https://jdvp.me/articles/Testing-Code-Tabs)

**Comment by Clement-Jean** [comment]
Great ! Thank you for working on that. Is there any way we could skip characters on a certain line too (sorry 😁). I'm saying that because I would like to skip the $ on my vommand line.

Or maybe we could add decorators on certain lines, inside certain code blocks 😁 ie: add $ on line 0 for shell code block

**Comment by jdvp** [comment]
Oh i hadn't considered that. Either option would be much more complicated than the line number thing already is so let me think about it
